# Generated by Django 3.2.13 on 2023-08-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
    ]
